### ISSUE TITLE
Crashes with Radium installed - Please Detail Fix in README

### ISSUE THREAD

**Issue by Tursiops-G** [Viola-Siemens/Dancing-Hoppers#1]
Please add the following to the README:

To prevent crashing with Radium mod installed, Disable Radium's Hopper Optimizations mixin by adding the following line to the instance's minecraft/config/lithium.properties file:
mixin.block.hopper=false
(Edited to correct typo error)

**Comment by Viola-Siemens** [comment]
> Please add the following to the README:
> 
> To prevent crashing with Lithium mod installed, Disable Lithium's Hopper optimizations by adding the following line to the instance's minecraft/config/lithium.properties file: mixin.block.hopper=false

Cannot reproduce. What version of Lithium are you using? Could you please upload the crash report and debug.log?

**Comment by Tursiops-G** [comment]
My Apologies... I should have said "Radium" (not "Lithium")... Radium adds/uses the "Lithium.properties" config file.
(I will correct my OP accordingly).

I'm using the latest release of Radium (radium-mc1.20.1-0.12.2+git.5f80f74.jar)
Crashes unless the above entry is made to the lithium.properties file.

Link to actual crash : https://mclo.gs/PbMxsLK
Debug Log: https://mclo.gs/q62ts12

**Comment by Viola-Siemens** [comment]
Ok, I tried Canary and the issue didn't happen. I've added it to README.

**Comment by Tursiops-G** [comment]
Thanks for the quick response. I'm sure others had this problem as well, and were thrown off by the Lithium reference when Radium is present instead. ;)
